apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-react-app-aks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alextsoh/node-react
    targetRevision: main
    path: App/k8s/kustomize/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
