# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: azure-kvname-wi
#   namespace: postgres
# spec:
#   provider: azure
#   parameters:
#     usePodIdentity: "false"
#     clientID: "${USER_ASSIGNED_CLIENT_ID}"  # Patched by kustomize
#     keyvaultName: ${KEYVAULT_NAME}  # Patched by kustomize
#     cloudName: ""
#     # objects:  
#       array:
#         - |
#           objectName: db-username
#           objectType: secret
#           objectVersion: ""
#         - |
#           objectName: db-password
#           objectType: secret
#           objectVersion: ""
#     tenantId: "${IDENTITY_TENANT}"  # Patched by kustomize