apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-app-secrets
  namespace: my-app # Must match your pod's namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false" 
    clientID: "fe82db3b-c013-4785-b9c5-c71ee9bf7993" # Your Managed ID Client ID
    keyvaultName: "myapp-prod-vault-01"             # <--- Change to your KV name
    tenantId: "7b0cb2bf-b6cb-4d8f-8666-f584b3dec443" # Your Tenant ID
    objects: |
      array:
        - |
          objectName: DB-URL-PROD                
          objectType: secret
          alias: database-password