apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: alextsoh/db-migrator:multiplatform
        imagePullPolicy: Always
        args:
          - -path=/app/migrations
          - -database=$(DATABASE_URL)
          - up
      restartPolicy: OnFailure