apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-db
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 1
  storage:
    size: 1Gi
  enableSuperuserAccess: true
  superuserSecret:
    name: pg-superuser-auth