apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
  namespace: my-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    matchLabels:
      app: api-node
  replicas: 1
  template:
    spec:
      containers:
      - name: api-node
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:safepassword@dev-cnpg-db-rw.dev-postgres.svc.cluster.local:5432/postgres?sslmode=disable"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
