apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-db
  namespace: dev-postgres
  annotations:
    kustomize.config.k8s.io/behavior: merge
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 1
  superuserSecret:
    name: dev-pg-superuser-auth