apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  annotations:
    argocd.argoproj.io/sync-wave: "0" # Runs first
spec:
  ttlSecondsAfterFinished: 3600 # Deletes 1 hour after finishing
  template:
    spec:
      containers:
        - name: migrator
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:safepassword@dev-cnpg-db-rw.postgres.svc.cluster.local:5432/postgres?sslmode=disable"