apiVersion: v1
kind: Secret
metadata:
  name: api-node-database-url
  namespace: my-app
stringData:
  DATABASE_URL: postgres://postgres:safepassword@prod-cnpg-db-rw.postgres.svc.cluster.local:5432/postgres?sslmode=disable
