apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node
  namespace: prod-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api-node
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
