# apiVersion: v1
# kind: Secret
# metadata:
#   name: api-node-database-url
#   namespace: my-app
# stringData:
#   DATABASE_URL: postgres://postgres:safepassword@prod-cnpg-db-rw.postgres.svc.cluster.local:5432/postgres?sslmode=disable

# !!!This file is no longer used as we are now using Azure Key Vault with the Secrets Store CSI Driver to manage our secrets.
# !!!The secret is now being mounted as a volume in the Deployment.yaml file and accessed via