apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-react-nginx
  namespace: prod-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: client-react-nginx
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
