# apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: my-app
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
        - name: migrator
          env:
            - name: DATABASE_URL_FILE
              value: "/mnt/secrets/DB-URL-PROD"
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "prod-my-app-secrets"