apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namePrefix: dev-
labels:
- pairs:
    environment: dev

images:
- name: api-node-placeholder
  newName: alextsoh/api-node
  newTag: 1.0.0-25-g996f02f
- name: client-react-placeholder
  newName: alextsoh/client-react
  newTag: 1.0.0-25-g996f02f

patches:
- path: patches/api-node-patch.yaml
- path: patches/client-react-patch.yaml
