apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namePrefix: dev-
labels:
  - pairs:
      environment: dev
patches:
  - path: patches/api-node-patch.yaml
  - path: patches/client-react-patch.yaml
