apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namePrefix: dev-
labels:
  - pairs:
      environment: dev
images:
  - name: api-node-placeholder       # Matches the image name in your base Deployment
    newName: alextsoh/api-node       # Your registry path
    newTag: initial                  # CI will overwrite this line automatically
  - name: client-react-placeholder
    newName: alextsoh/client-react
    newTag: initial
patches:
  - path: patches/api-node-patch.yaml
  - path: patches/client-react-patch.yaml
