apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- gateway.yaml
- httproute.yaml
- secret-provider-class-api.yaml
- secret-provider-class-postgres.yaml
- postgres-secret-sync.yaml
- service-account-postgres.yaml
- service-account-api.yaml
- Rollout.client-react.yaml
- Service-client-react-nginx-bluegreen.yaml

namePrefix: prod-

configMapGenerator:
- name: nginx-conf
  namespace: my-app
  files:
    - default.conf=nginx.conf

labels:
- pairs:
    environment: prod
images:
- name: api-node-placeholder
  newName: alextsoh/api-node
  newTag: 1.0.0-51-g7cdbe91
- name: client-react-placeholder
  newName: alextsoh/client-react
  newTag: 1.0.0-51-g7cdbe91
  
patches:
- path: patches/cnpg-cluster-patch.yaml
- path: patches/migrator-patch.yaml
- path: patches/api-node-patch.yaml
- path: patches/client-react-patch.yaml
- path: patches/client-react-deployment-disable.yaml


