apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-secret-sync
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-2" # runs before all other resources in ArgoCD sync
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: prod-postgres-workload-identity-sa # SA federated for Key Vault auth
      containers:
      - name: sync
        image: busybox
        command: ["true"] # Run and trigger the CSI driver to sync secrets
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets"
          readOnly: true
      restartPolicy: OnFailure
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "prod-postgres-secrets" # defines which Key Vault secrets to fetch and sync
