apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-workload-identity-sa
  namespace: postgres
  annotations:
    azure.workload.identity/client-id: "fe82db3b-c013-4785-b9c5-c71ee9bf7993"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-secret-sync
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: prod-postgres-workload-identity-sa
      containers:
      - name: sync
        image: busybox
        command: ["true"]
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets"
          readOnly: true
      restartPolicy: OnFailure
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "prod-postgres-secrets"
