apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-app-secrets
  namespace: my-app
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "fe82db3b-c013-4785-b9c5-c71ee9bf7993"
    keyvaultName: "myapp-prod-vault-01"
    tenantId: "7b0cb2bf-b6cb-4d8f-8666-f584b3dec443"
    objects: |
      array:
        - |
          objectName: DB-URL-PROD
          objectType: secret
          alias: database-password

  secretObjects:
    - secretName: my-app-secrets-sync
      type: Opaque
      data:
        - objectName: DB-URL-PROD # Name in Azure Key Vault
          key: DB_URL            # Key name inside the K8s secret

      #change 1