apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-workload-identity-sa
  namespace: postgres
  annotations:
    azure.workload.identity/client-id: "fe82db3b-c013-4785-b9c5-c71ee9bf7993"
    argocd.argoproj.io/sync-wave: "-3"
