name: image-ci

on:  
  push:
    branches: [main]
    paths: ['App/api-node/**','App/client-react/**']
  workflow_dispatch:

jobs:
  # STEP 1: Detect which folders actually changed
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      # This mapping tells the next jobs which services to run
      api-golang: ${{ steps.filter.outputs.api-golang }}
      api-node: ${{ steps.filter.outputs.api-node }}
      client-react: ${{ steps.filter.outputs.client-react }}
      postgresql: ${{ steps.filter.outputs.postgresql }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api-node: 'App/api-node/**'
            client-react: 'App/client-react/**'
            postgresql: 'App/postgresql/**'
            